create table product_types (
    product_type  text   PRIMARY KEY NOT NULL
);


CREATE SEQUENCE "products_id_seq"
    MINVALUE 1
    MAXVALUE 10000
    INCREMENT BY 10
    START WITH 1
    NOCACHE
NOCYCLE;

create table products
(
    id bigint generated by default as identity primary key,
    serial_number bigint not null,
    manafacturer text not null,
    price numeric not null,
    in_stock bigint,
    custom_properties json,
    product_type text not null references product_types(product_type)
);

